### ISSUE TITLE
Backend deployement

### ISSUE THREAD

**Issue by 07-Mayankraj** [deepakChourasiya-aj/melted-group-7444#40]
- [x] Token sending as object 
- [x] Finale check for github auth
- [x] Finale check for github auth
- [x] Make api as required 
- [x] update env and change confidentials 
- [x] deploye on Cyclic
- [x] merge Features to main server.js
> - [x] video chat
> - [x] screen sharing
> - [x] Chat features

- [x] .....

**Comment by 07-Mayankraj** [comment]
done
used microservices architecture overs monolith architecture

**Comment by deepakChourasiya-aj** [comment]
done
